package pl.cyfrowypolsat.cpcommon.domain.model.enums

enum class MediaBadgeType {
    UNDERAGE_CLASSIFICATION_VIOLENCE,
    UNDERAGE_CLASSIFICATION_DRUGS,
    UNDERAGE_CLASSIFICATION_SEX,
    UNDERAGE_CLASSIFICATION_VULGAR_LANGUAGE,
    ACCESSIBILITY_FEATURES_AUDIO_DESCRIPTION,
    ACCESSIBILITY_FEATURES_SUBTITLES,
    ACCESSIBILITY_FEATURES_SIGN_LANGUAGE
}